# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 008e2dab2951a8defb34b70ed14da6bfb092be3adb80059e0705a09074b9651980b77cfa604350671a8ff42f7ee6ead9d83e8fdbdacf87364ca6bd39e68053a1

test:
  secret_key_base: 60cd80a983661dcc24e5d731131127fb9179d5db9fde1ff32522dbc2879fd3f4860d53951a4c561ab2ad2157ce38f7d5a547d75e023a72b6a2e31c1e0f26d53d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
